### ISSUE TITLE
normalizedMethodNames sometimes "forgets" some of the names

### ISSUE THREAD

**Issue by tabatkins** [plinss/widlparser#10]
Given this Bikeshed document:

``` html
<pre class='metadata'>
Title: Test
Status: WD
TR: http://www.w3.org/TR/SpecName/
ED: http://www.w3.org/TR/SpecName
Previous Version: http://www.w3.org/TR/SpecName
Shortname: SpecName
Level: 1
Editor: John Doe, AnOrg., AnOrg@mail.com
Abstract: Abstract sentence
</pre>

<dfn method for=Foo>bar(index)</dfn>

<dfn method for=Foo>bar(name)</dfn>

<pre class=idl>
interface Foo {
    DOMString bar(long index);
    DOMString bar(DOMString name);
};
</pre>
```

You get a fatal error due to duplicated definitions.  Confusingly, this is because Bikeshed rewrites the _first_ `<dfn>` element to have `data-lt="bar(name)"`.  This happens because, in Bikeshed's `classifyDfns()` function, I ask the widl parser to normalize the linking text, using the line:

``` python
names = doc.widl.normalizedMethodNames(primaryDfnText, el.get('data-dfn-for'))
```

This ends up returning `"bar(name)"` for both `<dfn>` elements.  This only happens if the WebIDL block is present; without it, it correctly returns `"bar(index)"` for the first and `"bar(name)"` for the second.

What's up with this, yo?

**Comment by plinss** [comment]
The current implementation of findMethodNames finds the last method matching the name, and then returns it's 'methodNames', which is a list of all possible argument combinations. It's not looking for overrides of the method.

It's a fairly simple change to have it find all the matching methods and list all of their methodNames. My question for you is: do you want a simple concatenation of the methodNames or do you want them de-duped.

Example:

interface Foo {
  DOMString bar(long index, optional long length);
  DOMString bar(long index, optional DOMString search);
};

can give you either:
['bar(index)', 'bar(index, length)', 'bar(index)', 'bar(index, search)']

or:
['bar(index)', 'bar(index, length)', 'bar(index, search)']

(where the current implementation only gives you:
['bar(index)', 'bar(index, search)']
)

And go you care about the ordering of the results?

**Comment by plinss** [comment]
Alternatively I can group the results by method, if you need to differentiate between the overrides, like:
[['bar(index)', 'bar(index, length)'], ['bar(index)', 'bar(index, search)']]
(note that you'll always get a list of lists in this case, so a single result would still be [['bar(index)']])

**Comment by tabatkins** [comment]
Ah, so it only pays attention to the name, not the args.  That's what was confusing me.

All I'm really looking for is something to normalize the arglist.  I don't care about the overrides or what's parsed, I just want to remove the junk (like typenames) so I can correctly match it to one of the dfn texts.  It seems like I can get it to do this if I just use a fresh widlparser; should I just do that?

**Comment by plinss** [comment]
Using a fresh widlparser will only help if the definitions are in separate idl sections, you'll still have this problem if there are overridden methods or if there are two interfaces with the same method names in one section.

There are two other options, first, you can pass in the name of the interface as well, e.g.:
names = parser.normalizedMethodNames('bar', 'Foo')
and it will only pay attention to the last method named 'bar' in the interface 'Foo'.

Or if all you want is to normalize an arglist (and you have a fully defined arglist), you can pass that in and it will simply parse what's passed ignoring everything that may be previously parsed, e.g.:
names = parser.normalizedMethodNames('bar(long index, optional DOMString search)')

**Comment by plinss** [comment]
normalizeMethodNames() behavior has been updated: 

- If called with a complete method signature (argument types and names per WebIDL) it will process only what was passed and return all signature permutations, ignoring previously parsed WebIDL.

- If called with a method name followed by parentheses containing an optional list of argument names, it will match only previously parsed methods matching the names of the arguments (optional arguments may be omitted), all signatures of matching methods will be returned

- If called with a bare method name, it will match all methods with that name (in the first interface containing that method if the interface isn't specified), all signatures of matching methods will be returned

- If no matches are found, it will return what was passed, normalizing whitespace in the argument list (single space after comma)
