### ISSUE TITLE
Ability to mark up enum values?

### ISSUE THREAD

**Issue by tabatkins** [plinss/widlparser#12]
In <https://github.com/tabatkins/bikeshed/issues/628> someone is asking for the ability to define/link to the enumeration values.  It doesn't look like widlparser exposes them as something to be marked up right now, tho.  (If it does, it's not with one of the current markup* methods I know of.)

Any chance to get this?

**Comment by plinss** [comment]
Yeah, it's not currently doing any markup calls for the enum values, everything after the name is just once chunk of text. Easy to add though, the question is do we use one of the existing markup calls (none of which seem to really fit) or make a new one (and what do you want to call it?).

I don't really see anything else similar in WebIDL, so maybe just add markupEnumValue() and be done with it?

**Comment by tabatkins** [comment]
Fine with me.

**Comment by plinss** [comment]
Added in daf23f7b22c1d96e37e9391e3d554f040ee1a79a
