### ISSUE TITLE
Dictionary arguments must be marked as optional

### ISSUE THREAD

**Issue by annevk** [plinss/widlparser#16]
See https://github.com/whatwg/dom/issues/316 and https://github.com/heycam/webidl/issues/130 for an issue in the DOM Standard that was not caught by using bikeshed (which in turn uses widlparser as I understand it).

**Comment by plinss** [comment]
Added check in 549fcc8. I also added validation of required arguments following optional arguments while I was there.

Will work with @tabatkins to get integrated into Bikeshed as it might take some small code changes to work properly for disconnected idl blocks.

**Comment by tabatkins** [comment]
Bikeshed integration done.

**Comment by annevk** [comment]
Thanks y'all!

**Comment by plinss** [comment]
@annevk If there are more things like this that we can validate during parse, please file additional issues and I'll see what I can do. I didn't do a thorough read through of the spec when writing the parser (was more interested in getting data out than validation so I focused on the parsing), I'm supposing there will be a few.
