### ISSUE TITLE
Regression: "namespace" as method argument is now fatal

### ISSUE THREAD

**Issue by zcorpan** [plinss/widlparser#17]
Trying to build whatwg/dom with today's bikeshed gives

> FATAL ERROR: IDL SYNTAX ERROR LINE: 49 - skipped: "DOMString? lookupPrefix(DOMString? namespace)"

I assume this was introduced by https://github.com/plinss/widlparser/commit/133512a57ab0fcda7c6fb0788dae85a2a6b4aa26

cc @tabatkins

**Comment by plinss** [comment]
Right, the change added "namespace" as a terminal symbol. My understanding of the WebIDL spec implies that it's no longer available as an identifier. I'm willing to be convinced otherwise...

**Comment by plinss** [comment]
cc @heycam

What's the intention from the WebIDL perspective here?

**Comment by zcorpan** [comment]
The Web IDL spec says

> Operation arguments can take a slightly wider set of identifiers. In an operation declaration, the identifier of an argument is specified immediately after its type and is given by either an identifier token or by one of the keywords that match the ArgumentNameKeyword symbol. If one of these keywords is used, it need not be escaped with a leading underscore.

and has this example

``` 
// Interface identifier: "System"
interface System {

  // Operation identifier:          "createObject"
  // Operation argument identifier: "interface"
  object createObject(DOMString _interface);

  // Operation argument identifier: "interface"
  sequence<object> getObjects(DOMString interface);

  // Operation has no identifier; it declares a getter.
  getter DOMString (DOMString keyName);
};
```

(widlparser fails for this example at `sequence<object> getObjects(DOMString interface);`)

**Comment by zcorpan** [comment]
"namespace" is not in ArgumentNameKeyword but that may be an oversight? @bzbarsky @domenic

**Comment by bzbarsky** [comment]
That's totally an oversight.  In fact, I just missed it during my review of <https://github.com/heycam/webidl/pull/121/>; my implementation in Gecko included "namespace" in `ArgumentNameKeyword`.  Fixed this in the spec: https://github.com/heycam/webidl/commit/4e7cf6b06a3a230a92b78553190e60a48080fe69 and https://github.com/heycam/webidl/commit/dd77b1907e6af7ec27ff67edfb38f892f2fde3a8

That said, "interface" _is_ in `ArgumentNameKeyword`, so if widlparser is failing `sequence<object> getObjects(DOMString interface);` then it sounds like it needs to add support for `ArgumentNameKeyword` in general.

**Comment by bzbarsky** [comment]
No, looks like there's an `ArgumentNameKeywords` thing in widlparser already....  No idea why it's failing on @zcorpan's example.

**Comment by plinss** [comment]
Added "namespace" to ArgumentNameKeywords in e867c88. Couldn't reproduce @zcorpan's example with "interface" argument name.

Also added argument name escapes which I missed before.

Will integrate to Shepherd and Bikeshed later today when I finish the fix for #16

**Comment by zcorpan** [comment]
Maybe bikeshed was causing the error for "interface", I didn't test widlparser directly.

Thanks for fixing 😊

**Comment by plinss** [comment]
Please let me know if you're still seeing the issue with "interface" (and better if you have an example).

Shepherd has the new code, Bikeshed should be updated shortly.
