### ISSUE TITLE
The PrimitiveType construction isn't emitted in a useful manner

### ISSUE THREAD

**Issue by tabatkins** [plinss/widlparser#20]
Currently, the parts of a PrimitiveType (like `unsigned long long`) are emitted as individual keyword tokens. This makes it impossible to mark them up as autolinks without significant post-parse fiddling.

Is there any way to get them emitted as a unit, presumably triggering the `markupTypeName()` method?

**Comment by plinss** [comment]
Yeah, should be doable. IIRC markupTypeName was for the name of custom types so not sure offhand if its the best markup method. But I'll take a look. It'll take a few days before I can get to it though.
