### ISSUE TITLE
Add support for readonly attributes in namespaces

### ISSUE THREAD

**Issue by domenic** [plinss/widlparser#21]
See https://github.com/heycam/webidl/pull/264 and in particular https://github.com/heycam/webidl/pull/264/commits/35a37c33aba82993b4f7cb9e6d17430199ed82d9 and in particular the new grammar line at https://github.com/heycam/webidl/pull/264/commits/35a37c33aba82993b4f7cb9e6d17430199ed82d9#diff-ec9cfa5f3f35ec1f84feb2e59686c34dR4057

**Comment by domenic** [comment]
You're the best @plinss! @tabatkins how do we get this pulled into Bikeshed and the web service?

**Comment by plinss** [comment]
I'm planning on fixing #20 today too, I'll ping @tabatkins about pulling it into Bikeshed when I'm done. The web service gets all changes on a web hook automatically.
