### ISSUE TITLE
Confusing vararg signature

### ISSUE THREAD

**Issue by tabatkins** [plinss/widlparser#23]
Given IDL with a vararg argument, like:

```
interface Foo {
    DOMString bar(short baz, long... qux);
};
```

If you then ask for normalized names, it'll pop out `"bar(baz)"` and `bar(baz, qux...)`.

Is this intentional?  While the IDL type has suffix-ellipsises, I think it makes more sense for the argname to use prefix ellipsises, matching JS patterns.

Context: https://github.com/tabatkins/bikeshed/issues/838

**Comment by plinss** [comment]
btw, I also fixed normalizedMethodNames to always return lists (instead of sometimes a generator), so you can remove that list conversion in bikeshed
