### ISSUE TITLE
Support annotated types

### ISSUE THREAD

**Issue by domenic** [plinss/widlparser#24]
These were added to Web IDL in https://github.com/heycam/webidl/pull/286. The grammar should have you covered.

This will help us move Bikeshed specs to the new syntax (which is, e.g., `attribute [TreatNullAs=EmptyString] DOMString data` instead of `[TreatNullAs=EmptyString] attribute DOMString data`).

**Comment by plinss** [comment]
Ping @tabatkins to include in Bikeshed

**Comment by tabatkins** [comment]
Added and pushed.
