### ISSUE TITLE
construct.extendedAttributes shouldn't ever be None

### ISSUE THREAD

**Issue by tabatkins** [plinss/widlparser#30]
Construct.extendedAttributes is None if there aren't any extended attributes at all. This is inconvenient when trying to loop over the extended attributes, as you have to catch the None case explicitly.  Can we remove that, and just make it an empty list? That gives the same bool behavior, but is way more convenient in loops.

(The only thing I can imagine is that it's there to distinguish between an empty extended attribute list, and no extended attributes at all. Is that the point?)

**Comment by plinss** [comment]
Not sure it was a conscious decision, but looking at the ExtendedAttribute parsing code it would consider `[]` to be legal, though it then creates a list with one `ExtendedAttributeUnknown()` in it (which stores zero tokens), so there would never be an empty list. I changed to just return an empty dict (the actual return type is an ExtendedAttributeList(), which is dict-like) in the api but store a `None` internally for behavioral reasons (markup and unicode output).

**Comment by tabatkins** [comment]
Danke!
