### ISSUE TITLE
New ReadonlyAttribute construct incorrectly requires readonly

### ISSUE THREAD

**Issue by tabatkins** [plinss/widlparser#34]
In <https://github.com/plinss/widlparser/commit/b144ef226a7fd98f9c404fd385eaf99719988a82#diff-3765dfb6cf973a183c6695291aec260aR1320> (commit adding support for mixins), the ReadonlyMember construct was added. However, in the WebIDL grammar, `ReadonlyMember` has an *optional* `readonly` in front; in widlparser, it's required.

I'll see about submitting a fix, just logging the issue first.

**Comment by plinss** [comment]
Since AttributeRest already handles the optional `readonly`, the fix should be simple, just remove the `Symbol.peek(tokens, 'readonly')` from the Peek method of Readonly Attribute. And rename the class to MixinAttribute.
