### ISSUE TITLE
Date, RegExp are no longer part of the grammar

### ISSUE THREAD

**Issue by Ms2ger** [plinss/widlparser#36]
https://github.com/heycam/webidl/pull/69
https://github.com/heycam/webidl/pull/220

**Comment by Ms2ger** [comment]
Fixed in https://github.com/plinss/widlparser/commit/a5df7f1cbc0b6b1eaa74311b57113caeb87db30a?

**Comment by plinss** [comment]
Actually fixed in be7b5d7e9488c966761adffb2c19db9a274b6481 by @vinyldarkscratch
