### ISSUE TITLE
Support Python 3

### ISSUE THREAD

**Issue by dominiccooney** [plinss/widlparser#40]
Here are things I believe are necessary to support Python 3:

- Use the dot-import syntax for relative imports. Python 3 uses absolute imports so things like `import parser` now import Python's AST parser.
- Use `str` instead of 'basestr` and `unicode`. Maybe the error messages shouldn't collapse identifiers to ASCII any more, either. There's a popular third-party module, six, which has some helpers for this.
- Use `__bool__` instead of `__nonzero__`.

**Comment by foolip** [comment]
@tabatkins, is widlparser the only Bikeshed dependency that doesn't support py3?

**Comment by plinss** [comment]
Fixed in a6885e85aea4d3c571648fe65b884b2dce2a7f3b
