### ISSUE TITLE
Underscores incorrectly stripped from member names

### ISSUE THREAD

**Issue by foolip** [plinss/widlparser#51]
https://github.com/plinss/widlparser/pull/50 adds some test IDL demonstrating the problem:
```idl
interface Underscores {
  attribute DOMString _or;
  boolean _includes(DOMString value);
};
```

This regressed in 1e12438e7f9a12f6911df2b90859e7d75a867c46, and reverting that commit results in these changes to the expected output:
```diff
 interface: Underscores
-    attribute: or (or)
-    method: includes(value) (includes)
+    attribute: _or (_or)
+    method: _includes(value) (_includes)
```

However, that commit also fixed things around whitespaces, so just reverting it won't do.

**Comment by plinss** [comment]
As I understand it, this behavior is correct per the WebIDL spec: https://heycam.github.io/webidl/#ref-for-dfn-identifier

**Comment by plinss** [comment]
hmm, actually maybe that's only supposed to apply to operations...

**Comment by Ms2ger** [comment]
@foolip how is it incorrect? The actual identifiers are "or" and "includes".

**Comment by foolip** [comment]
@Ms2ger I spotted it as a regression of Bikeshed tests, but I'm not totally sure widlparser is wrong, could also be that Bikeshed needs to use it differently now. I've pushed the differnces to https://github.com/tabatkins/bikeshed/pull/1514 and will comment there, perhaps that'll help identify what exactly is wrong.

**Comment by foolip** [comment]
Note also that in https://github.com/plinss/widlparser/pull/50 the underscore appears in some places, so I guess the AST has two representations and Bikeshed needs to use the right one in the right context.

**Comment by foolip** [comment]
@plinss was the change regarding underscores intended in https://github.com/plinss/widlparser/commit/1e12438e7f9a12f6911df2b90859e7d75a867c46? Nothing in the change or commit message immediately suggests it.

**Comment by plinss** [comment]
It was somewhat unintentional as I was copy/pasting some code to switch the names over to production classes rather than bare tokens. This brought in the fix handling identifier escaping, which I believe is actually correct.

What I need to do now is run through the code checking if there are other places that should be supporting identifier escaping but aren't (and probably factor out the identifier escape handling).

**Comment by plinss** [comment]
Ok, there were a *bunch* of places that I wasn't properly handing escaped identifiers. Fixed now. This will likely break some more tests in Bikeshed but I believe the widlparser behavior is correct. Please re-open or file another issue if I got something wrong.

**Comment by foolip** [comment]
Alright, I'll try rolling the changes in https://github.com/plinss/widlparser/commit/8f5e3cc5cb757464a71715de348be76989b74414 as well.

**Comment by foolip** [comment]
Another thing broken now. Follow https://github.com/tabatkins/bikeshed/pull/1514#issuecomment-527808315 if you're interested in this rolling into Bikshed.
