### ISSUE TITLE
constructor() acts like a keyword, not a method

### ISSUE THREAD

**Issue by tabatkins** [plinss/widlparser#53]
`constructor()` is emitted in a weird way that makes my life harder in Bikeshed.

First, the `constructor` part is processed by markupKeyword, not markupName like method names are.  That's not too bad - I've already written code to handle it - but it's still a little weird. This doesn't necessarily need to change, I suppose.

Second and much more importantly, the arguments to the constructor don't consider the constructor to be their parent construct; instead they think the *interface* is their parent.  This seems weird, since the whole constructor *is* recognized as a "method" construct. This means that I don't have any easy way to get the method names so I can generate the `for` values for the argument dfns.

**Comment by plinss** [comment]
I can wrap the keyword in a `<name>` as well, e.g.
  `<construct type=method><name><keyword>constructor</keyword></name>();</construct>`
would that make sense?

Will take a look at the argument's parent, that's just a bug.

**Comment by tabatkins** [comment]
Hmmm yeah, wrapping in a name would probably work, I'd have to see how my stuff responds to that.

**Comment by plinss** [comment]
I can also just change it to replace the keyword wrapping with the name (which would actually be easier, but seems wrong to have a keyword that isn't wrapped)

**Comment by tabatkins** [comment]
For all intents and purposes this is a method name; it's just kinda magically named. I'm fine with it not recognizing itself as a keyword; I don't remember if highlighting treats keywords and method names differently, but if it does, I'd prefer it to look like a method not a keyword.

**Comment by plinss** [comment]
fixed by 7f88353e1b389fde98ac6948fc08df7765d4a4de and a2786567b9415c820115fc6500453f91e52772be
