### ISSUE TITLE
What is the correct way to get the markup for just the value of a Default?

### ISSUE THREAD

**Issue by emlun** [plinss/widlparser#54]
Hi! In tabatkins/bikeshed#1592, we have the issue that the `value` member of a [`Default`](https://github.com/plinss/widlparser/blob/master/widlparser/productions.py#L1085) is `None` if the `Default` has [the value `[]` or `{}`](https://github.com/plinss/widlparser/blob/7f88353e1b389fde98ac6948fc08df7765d4a4de/widlparser/productions.py#L1108-L1115). There doesn't seem to be a clean way to get the markup for just the value - `unicode(default)` gets close, but that also includes the equals sign and maybe some whitespace.

For reference, the calling code is [here](https://github.com/tabatkins/bikeshed/blob/2a881f0ee698433d75c6a1555514334adb37d8c7/bikeshed/idl.py#L158-L160).

This works (`v` would replace `construct.default.value` at the above link), but it relies on internal implementation details:

```
v = default.value if default.value else (default._open.symbol + default._close.symbol)
```

This almost does what I want:

```
default = Default(...)
v = unicode(default).split('=', 1)[1].strip()
```

except it also includes any whitespace embedded within a `[]`. For tests, it would be nice to get the value with all whitespace stripped out - unless it's a string literal, in which case you'd only trim leading and trailing whitespace. Does that make sense to include as a method in the library, or should we do it on the caller side instead?

**Comment by plinss** [comment]
Fixed in 3c439d883f2700c07e5507ffb49f34938eb44451, Default.value should now return '{}' or '[]' without whitespace for those default values

**Comment by plinss** [comment]
@tabatkins since this fix is in the Python3 port, let me know if you need it backported to the python2 branch

**Comment by tabatkins** [comment]
nah i plan to finish the port next week, it's fine
