### ISSUE TITLE
Add ObservableArray<> to the grammar

### ISSUE THREAD

**Issue by domenic** [plinss/widlparser#55]
https://github.com/heycam/webidl/commit/e6ae134ad470118565b70b2c876a601b9f716187 adds one new line to the grammar: https://github.com/heycam/webidl/commit/e6ae134ad470118565b70b2c876a601b9f716187#diff-ec9cfa5f3f35ec1f84feb2e59686c34dR5768

**Comment by tabatkins** [comment]
This patch allows `ObservableArray` in method return types, but not in attribute types.

**Comment by tabatkins** [comment]
Never mind, I was misspelling it. :(
