### ISSUE TITLE
Make “markup” consumer code with wrong method names hard-fail?

### ISSUE THREAD

**Issue by sideshowbarker** [plinss/widlparser#59]
To prevent consumer code for the “markup” feature of widlparser from silently just not working if the wrong method names are used, it would seem to be useful to have the behavior be that using the wrong method names causes a hard fail of some kind — throwing an exception, I guess.

Or maybe even better it should be something that can be caught through static analysis — so any Python IDE can flag it as a compile-time error. 

Context: When testing https://github.com/tabatkins/highlighter with the HTML spec, I noticed it wasn’t generating syntax-highlighting any of the WebIDL blocks in the HTML — but it also wasn’t throwing any exceptions nor reporting any error messages.

It took me relatively a lot of time to finally figure out the cause was that the highlighter was using some camelCase “method” names that per https://github.com/plinss/widlparser/blob/master/README.md#markup need to be snake case.

I guess the highlighter code had it that way because it had previously been importing an older widlparser version which expected camelCase method names — but subsequently (recently) the highlighter code switched to importing the current widlparser version, in which the expected names had changed to being in snake case.

So at https://github.com/tabatkins/highlighter/pull/17/commits/b8754fcdccc414b37e288eddcc73790b8d9983ba I wrote a highlighter patch that fixed it. But it has left me wondering if there is some way to help writers of consumer case avoid running into a problem like that. Maybe some existing built-Pythonic way?

I think in other languages/runtimes, that problem I ran into is maybe the kind of thing that can be avoided by having abstract classes — and consumer code then defines and uses implementations of those abstract classes. And if the implementation in the consumer code doesn’t have the required methods from the abstract class, it’s a compile-time error.

I see at https://docs.python.org/3/library/abc.html that Python3 now has abstract classes — so maybe that’s a possible/suitable solution here.

…or maybe abstract classes are not suitable at all in this case and maybe instead there’s some other existing Pythonic way to deal with something like this.

**Comment by plinss** [comment]
In this case since I'm already detecting if the marker implements the markup methods, I should just check for the old methods as well and call them, maybe emit a 'deprecated' warning when I fall back to those.

IIRC there's a protocol definition for the marker, I think a static analysis checker like mypy should already detect that the marker passed doesn't implement the protocol.

**Comment by sideshowbarker** [comment]
Thanks!
