### ISSUE TITLE
No trailing space when generating markup for "any" type

### ISSUE THREAD

**Issue by beverloo** [plinss/widlparser#6]
Given the following IDL example:
```
dictionary MyDictionary {
    any value = null;
};
```

When generating markup for the "value" entry, no trailing space gets included after the `any` type. E.g.:

```
anyvalue = null;
```

In MarkupGenerator.addType() the type._trailingSpace property seems to be set for non-`any` types, but not for `any`.

**Comment by plinss** [comment]
Fixed in commit 158f04a

**Comment by beverloo** [comment]
Great, thank you Peter!

**Comment by plinss** [comment]
Thank you for the bug report (and the fix for required DictMembers).

These changes will show up in Bikeshed once Tab lands https://github.com/tabatkins/bikeshed/pull/375
