### ISSUE TITLE
Add support for constants on namespaces

### ISSUE THREAD

**Issue by domenic** [plinss/widlparser#66]
https://github.com/heycam/webidl/commit/452e8bd02b5e85f9ba608a3614471633581dc839#diff-5e793325cd2bfc452e268a4aa2f02b4024dd9584bd1db3c2595f61f1ecf7b985R4772

```diff
    NamespaceMember :
        RegularOperation
        "readonly" AttributeRest
+        Const
```

**Comment by kainino0x** [comment]
This change is blocking a change in the WebGPU spec, any chance we could get it added? (I can try to help if someone can point me to the right place.)

**Comment by kainino0x** [comment]
Thank you!!
