### ISSUE TITLE
[Exposed=Window] and [Exposed=(Window,Worker)] treated differently

### ISSUE THREAD

**Issue by tabatkins** [plinss/widlparser#7]
If I write an interface with `[Exposed=Window]`, the Window gets marked up as a type name.  The same does not occur for `[Exposed=(Window,Worker)]`.

When using the debug marker, the structures exposed for each are:

```html
<extended-attribute>
      <name for="extended-attribute">Exposed</name>
      =
      <type-name for="extended-attribute">Window</type-name>
     </extended-attribute>
```

and 

```html
<extended-attribute>Exposed=(Window, Worker)</extended-attribute>
```

I think both should be linked?

**Comment by annevk** [comment]
Actually, unless they link to the thing that says [Global=Window] or [Global=Window] it probably doesn't make sense to link them.

**Comment by tabatkins** [comment]
Oh yeah, forgot that the identifier there isn't an interface name, but a [Global]-defined token.

**Comment by plinss** [comment]
Ok, so commit baa56e9 adds support for ExtendedAttributeIdentList which gets marked up as ExtendedAttrinbuteIdent. So now they'll both be type names. 

Should widlparser markup neither as type names or do you want to handle the linking in Bikeshed?

**Comment by tabatkins** [comment]
I'll handle it myself, as I can just walk up the construct tree and tell I'm in an Exposed attribute.  For now I won't link them, but I'll look into what I need to do to link them later.

**Comment by annevk** [comment]
I don't know. E.g. Worker would need to link to https://html.spec.whatwg.org/#dedicatedworkerglobalscope and not https://html.spec.whatwg.org/#worker for this to be somewhat accurate.

**Comment by plinss** [comment]
Ok, let me know if you want me to change the markup type of those idents

**Comment by tabatkins** [comment]
Nah, type-name is correct, as it's a non-defining instance of the name.  It's just a type that we don't know how to recognize yet. ^_^

**Comment by tabatkins** [comment]
@annevk Yeah, in order to start linking this, I'll first have to start recognizing the `[Global]` annotation and marking it up with some new type of definition.  That wont' happen for a bit, but I'll file a bug on myself to track it.
