### ISSUE TITLE
Parser incorrectly emits a warning for a trailing comma on EnumValueList

### ISSUE THREAD

**Issue by tabatkins** [plinss/widlparser#75]
This has been the case for a few years, see <https://github.com/plinss/widlparser/blame/main/widlparser/productions.py#L733>, but it wasn't visible in Bikeshed since I didn't supply a warn() method on my marker class.

I don't know why this is warned as a "LEGACY IDL" thing, it's just a normal part of the grammar. I'll submit a PR in a bit to remove the warning.

**Comment by tabatkins** [comment]
(This showed up in author content in <https://github.com/tabatkins/bikeshed/issues/2287>.)

**Comment by kainino0x** [comment]
This was fixed by https://github.com/plinss/widlparser/pull/76
