### ISSUE TITLE
Getting correct argument list of a method

### ISSUE THREAD

**Issue by redcrabs** [plinss/widlparser#78]
Hello .

For Web-GPU and createBuffer method I'm using the following code to get the the full name of arguments based on the documentation.

`print(parser.normalized_method_name('createBuffer')) `

The result would be :

` createBuffer(descriptor) `

However, based on the documentation, the IDL type of the descriptor (as argument) in this case for `createBuffer` is `GPUBufferDescriptor` , how is possible that I can get it ? 

Thanks!

**Comment by plinss** [comment]
`normalizedMethodName` explicitly removes the types from the method signature, it was made as a utility function for Bikeshed.

If you want details about each argument, you should query the argument list directly from the method. You can get the method via:
`create_buffer = parser.find('createBuffer')` (or by querying the interface construct)

then use:
`create_buffer.arguments` to get an ArgumentList, which (despite the name) is dict-like.

or you can simply call:
`parser.find_arguments('createBuffer')` to get a list of the arguments and iterate them.

Once you have the argument, it has `name` and `type` properties.
