### ISSUE TITLE
Add distinguishing between callback and dictionary-like types

### ISSUE THREAD

**Issue by vmpstr** [plinss/widlparser#84]
WebIDL recently changed due to https://github.com/whatwg/webidl/pull/1353 to allow distinguishing callback and dictionary-like types. Details are on the PR

**Comment by plinss** [comment]
I took a quick look at that PR, and it's not clear what, if any changes need to be made in widlparser for this. Can you elaborate?

**Comment by plinss** [comment]
widlparser doesn't so that level of validation at this point, so nothing to do. Thanks for checking tho.
