### ISSUE TITLE
Some nullable types in attribute declarations don't parse

### ISSUE THREAD

**Issue by tabatkins** [plinss/widlparser#9]
In the code:

```
interface Int {
  readonly attribute long? service;
  readonly attribute ArrayBuffer? value;
  readonly attribute ArrayBuffer value2;
  attribute ArrayBuffer? value3;
};
```

the parser throws a syntax error for lines 3 and 5, the two with nullable ArrayBuffers.  Removing the `?` from either removes the error; adding a `?` to line 4 makes it fail as well.

These appear to be completely legal per the idl spec.

**Comment by plinss** [comment]
FIxed in 7eee9c8
